<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Cavista.CTRecruita.Data\Cavista.CTRecruita.Data.csproj" />
    <ProjectReference Include="..\Cavista.CTRecruita.Utilities\Cavista.CTRecruita.Utilities.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
